# frozen_string_literal: true

DEBUGGING = ENV.fetch("DEBUG", "false").casecmp("true").zero?

# External gems
require "debug" if DEBUGGING
require "silent_stream"
require "rspec/block_is_expected"
require "rspec/block_is_expected/matchers/not"
require "rspec/stubbed_env"
require "fileutils"

# NOTE: GemMine will be moved into a separate gem, so it can have discrete tests and coverage.
require "gem_mine"

# Config files
require "config/timecop"
require "support/bench_gems_generator"
require "support/classes/spec_struct"
require "support/helpers/activation_events_helper"
require "support/helpers/contraindications_helper"
require "support/helpers/floss_funding_helper"
require "support/spec_only_writers"

IS_CI = ENV.fetch("CI", "false").casecmp("true") == 0

RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  config.include(SilentStream)

  # Exclude examples/groups tagged with :skip_ci when running on CI
  # Usage: add `:skip_ci` to any example or group you want to skip on CI
  if IS_CI
    config.filter_run_excluding :skip_ci => true
  end

  # Reset global state around each example to avoid cross-test pollution
  config.around do |example|
    begin
      # Snapshot state
      saved_namespaces = nil
      saved_silenced = nil
      saved_time = nil
      if defined?(FlossFunding)
        saved_namespaces = FlossFunding.namespaces
        saved_silenced = FlossFunding.silenced
        saved_time = FlossFunding.loaded_at
      end

      if example.metadata[:deterministic_time]
        # Deterministic time source
        time = example.metadata[:deterministic_time].is_a?(Time) ? example.metadata[:deterministic_time] : Time.utc(2025, 1, 1, 0, 0, 0)
        FlossFunding.instance_variable_set(:@loaded_at, time)
      end

      # Silence STDOUT for examples NOT tagged with :check_output
      if DEBUGGING || example.metadata[:check_output]
        example.run
      else
        silence_stream($stdout) do
          example.run
        end
      end
    ensure
      # Restore state
      if defined?(FlossFunding)
        FlossFunding.namespaces = saved_namespaces || {}
        FlossFunding.silenced = saved_silenced
        FlossFunding.instance_variable_set(:@loaded_at, saved_time)
      end
    end
  end

  # Cleanup autogenerated gems after the entire suite
  config.after(:suite) do
    begin
      if ENV.fetch("AUTOGEN_FIXTURE_CLEANUP", "false").casecmp("true").zero?
        gem_mine_root = File.expand_path(File.join(__dir__, "fixtures", "gem_mine"))
        if File.directory?(gem_mine_root)
          # Remove everything inside gem_mine_root, but keep the directory itself
          Dir.glob(File.join(gem_mine_root, "*"), File::FNM_DOTMATCH).each do |entry|
            base = File.basename(entry)
            next if base == "." || base == ".."
            FileUtils.rm_rf(entry)
          end
        end
      else
        puts "Skipping autogenerated gem fixture cleanup (AUTOGEN_FIXTURE_CLEANUP=false)"
      end
    rescue StandardError => e
      warn "test cleanup warning: #{e.class}: #{e.message}"
    end
  end
end

# Generate the 100 gem fixtures on disk (idempotent)
FlossFunding::BenchGemsGenerator.generate_all

# Within the test suite, we will consider this gem to be activated
ENV["FLOSS_FUNDING_FLOSS_FUNDING"] = "Free-as-in-beer"

# NOTE: Gemfiles for older rubies won't have kettle-soup-cover.
#       The rescue LoadError handles that scenario.
begin
  require "kettle-soup-cover"
  require "simplecov" if Kettle::Soup::Cover::DO_COV # `.simplecov` is run here!
rescue LoadError => error
  # check the error message and re-raise when unexpected
  raise error unless error.message.include?("kettle")
end

require "floss_funding"
